//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAuditLog
    {
        public int LogID { get; set; }
        public int ProductID { get; set; }
        public int WarehouseID { get; set; }
        public int OldQuantity { get; set; }
        public int NewQuantity { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
