//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ProductID { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<int> QuantityOnHand { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
