//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryProjectDBEntities : DbContext
    {
        public InventoryProjectDBEntities()
            : base("name=InventoryProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InventoryAuditLog> InventoryAuditLogs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<SalesOrderItem> SalesOrderItems { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<vw_OrderDetails> vw_OrderDetails { get; set; }
        public virtual DbSet<vw_ProductSalesSummary> vw_ProductSalesSummary { get; set; }
    
        public virtual int sp_AddNewProduct(string sKU, string name, Nullable<decimal> price, string desc)
        {
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddNewProduct", sKUParameter, nameParameter, priceParameter, descParameter);
        }
    
        public virtual int sp_PlaceOrder(Nullable<int> customerID, Nullable<int> productID, Nullable<int> warehouseID, Nullable<int> quantity)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var warehouseIDParameter = warehouseID.HasValue ?
                new ObjectParameter("WarehouseID", warehouseID) :
                new ObjectParameter("WarehouseID", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PlaceOrder", customerIDParameter, productIDParameter, warehouseIDParameter, quantityParameter);
        }
    
        public virtual ObjectResult<spTopCustomers_Result> spTopCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTopCustomers_Result>("spTopCustomers");
        }
    
        public virtual ObjectResult<spWarehouseLoad_Result> spWarehouseLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spWarehouseLoad_Result>("spWarehouseLoad");
        }
    }
}
