//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderDetails
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string ProductName { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
    }
}
