//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductSalesSummary
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string SKU { get; set; }
        public Nullable<int> TotalQuantitySold { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
    }
}
